### ISSUE TITLE
Error went start listener

### ISSUE THREAD

**Issue by tugdualnicolas** [tiagorlampert/CHAOS#1]
Running on a Linux vps

```
START LISTENER
 --------------------------

 [*] Enter LPORT: [IP]

 [*] Waiting for connection...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4fb850]

goroutine 1 [running]:
main.RunServer()
	/root/CHAOS/CHAOS.go:503 +0x6d0
main.GenerateCode()
	/root/CHAOS/CHAOS.go:475 +0x3985
main.ShowMenu()
	/root/CHAOS/CHAOS.go:165 +0x975
main.ShowMenu()
	/root/CHAOS/CHAOS.go:175 +0x93f
main.main()
	/root/CHAOS/CHAOS.go:41 +0x2a
exit status 2

```

**Comment by tiagorlampert** [comment]
In "[*] Enter LPORT: "
Do you have put the IP correctly? Or put _[IP]_

Sample:

```
START LISTENER
 --------------------------

 [*] Enter LPORT: **# 111.111.111.11**

 [*] Waiting for connection...

```
